### ISSUE TITLE
RAP file is not included in repository.  This is needed for users who cannot build on their own.

### ISSUE THREAD

**Issue by ScottMonaghan** [Milyli/RelativityScriptRunner#4]

**Comment by brycekbargar** [comment]
We started uploading our release RAP files using GitHub Releases, you can always find the latest one here: https://github.com/Milyli/RelativityScriptRunner/releases/latest .

We've also implemented an automated build process in TFS to make sure that the latest release consistently gets pushed to GitHub going forward as part of issue #11
