### ISSUE TITLE
All scripts error when clicking on them.  Contact me for more details.

### ISSUE THREAD

**Issue by ScottMonaghan** [Milyli/RelativityScriptRunner#8]
![image](https://user-images.githubusercontent.com/1868388/38428618-d70d54a4-3981-11e8-8ee8-aa59f05d2c5f.png)

**Comment by brycekbargar** [comment]
This was fixed as part of the [1.0.44 Release of ScriptRunner](https://github.com/Milyli/RelativityScriptRunner/releases/tag/1.0.0.44).
